name: UIFLOW2 Firmware Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.3.0

    - name: Install packages
      run: source tools/ci.sh && ci_esp32_idf504_setup

    - name: Build
      run: source tools/ci.sh && ci_esp32_nightly_build

    - name: Upload firmware
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ./m5stack/build-M5STACK_AirQ/uiflow-*-*.bin
          ./m5stack/build-M5STACK_Atom_Echo/uiflow-*-*.bin
